Repository BHSRobotix/RapidReact2022, pull requests merged in 2022-02, with the labels that each got.

#12 Add PathPlanner Library
  .idea/jarRepositories.xml
  src/main/deploy/pathplanner/New Path.path
  src/main/deploy/pathplanner/generatedCSV/New Path.csv
  src/main/deploy/pathplanner/generatedJSON/New Path.wpilib.json
  vendordeps/PathplannerLib.json
Labels: Enhancement

#14 DriveTrain Changes + Working Shooter
  .idea/runConfigurations.xml
  .vscode/settings.json
  build.gradle
  src/main/java/bhs/devilbotz/Robot.java
  src/main/java/bhs/devilbotz/RobotContainer.java
  src/main/java/bhs/devilbotz/commands/DriveCommand.java
  src/main/java/bhs/devilbotz/commands/shooter/Shoot.java
  src/main/java/bhs/devilbotz/commands/shooter/ShooterIdle.java
  src/main/java/bhs/devilbotz/subsystems/DriveTrain.java
  src/main/java/bhs/devilbotz/subsystems/Indexing.java
  src/main/java/bhs/devilbotz/subsystems/Intake.java
  src/main/java/bhs/devilbotz/subsystems/Shooter.java
Labels: Enhancement, Bug Fix

#18 Fix Log Error
  src/main/java/bhs/devilbotz/subsystems/DriveTrain.java
Labels: Bug Fix

#19 Reset Talon Config Auto. and apply default settings
  src/main/java/bhs/devilbotz/subsystems/DriveTrain.java
Labels: Enhancement

#17 Reformat code to follow a single consistant style
  src/main/java/bhs/devilbotz/RobotContainer.java
  src/main/java/bhs/devilbotz/commands/autonomous/drive/DriveDistance.java
  src/main/java/bhs/devilbotz/commands/autonomous/drive/DriveRotate.java
  src/main/java/bhs/devilbotz/commands/autonomous/drive/DriveTimed.java
  src/main/java/bhs/devilbotz/commands/autonomous/routines/AutoTest.java
  src/main/java/bhs/devilbotz/commands/climber/ClimberIdle.java
  src/main/java/bhs/devilbotz/commands/climber/LowerHook.java
  src/main/java/bhs/devilbotz/commands/climber/RaiseHook.java
  src/main/java/bhs/devilbotz/commands/intake/IntakeIdle.java
  src/main/java/bhs/devilbotz/commands/intake/IntakeIn.java
  src/main/java/bhs/devilbotz/commands/intake/IntakeOut.java
  src/main/java/bhs/devilbotz/commands/shooter/Shoot.java
  src/main/java/bhs/devilbotz/subsystems/DriveTrain.java
  src/main/java/bhs/devilbotz/subsystems/Indexing.java
  src/main/java/bhs/devilbotz/subsystems/Intake.java
  src/main/java/bhs/devilbotz/subsystems/PowerDistributionPanel.java
  src/main/java/bhs/devilbotz/subsystems/Shooter.java
Labels: Formatting

#22 Talon srx drivetrain shuffleboard
  .gitignore
  .idea/runConfigurations.xml
  simgui.json
  src/main/java/bhs/devilbotz/RobotContainer.java
  src/main/java/bhs/devilbotz/subsystems/DriveTrain.java
  src/main/java/bhs/devilbotz/subsystems/PowerDistributionPanel.java
  src/main/java/bhs/devilbotz/subsystems/SparkMaxDiagnostic.java
  src/main/java/bhs/devilbotz/subsystems/TalonSrxDiagnostic.java
Labels: Bug, Enhancement
